### ISSUE TITLE
Custom build variant like `prodDebug` / `prodRelease` cannot be set 

### ISSUE THREAD

**Issue by talhahasanzia** [Guardsquare/bitrise-step-scan-with-appsweep#3] opened 2024-02-13 14:45 UTC
The step has only option is to select `debug` which runs `uploadToAppSweepDebug` and `release` which runs `uploadToAppSweepRelease`.

I have `prodRelease` variant and I cant even run it, seems like only fix for now for me is `Gradle Runner` step.

I have also tried setting an environment variable to `prodRelease` in variant option in step but it is still useless. I was expecting it will replace `release` with `prodRelease`, but no luck.

**Comment by DoHuberGS** [comment] 2024-04-04 12:52
Duplicate of #1 
Fix coming soon, stay tuned!

**Comment by DoHuberGS** [comment] 2024-04-04 12:52
Wrong close status

**Closed as completed by DoHuberGS** 2024-04-04 12:52 UTC
